config/routes.rb
Rottenpotatoes::Application.routes.draw do
  resources :movies
  root :to => redirect('/movies')
  resources :users
  root :to => redirect('/users')
  match '/login',to: 'sessions#new',via: :get
  match '/login_create',to: 'sessions#create',via: :post
  match '/logout',to: 'sessions#destroy',via: :delete

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title, :rating, :description, :release_date
end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessible :user_id,:email,:session_token

def User::create_user!(vari={})
	vari[:session_token]=SecureRandom.base64
	@user=User.create!(vari)
	return @user
end




end

app/controllers/SessionsController.rb
class SessionsController < ApplicationController


 def new
  # default: render 'new' template
 end

 def create

   vari=params[:user]
   var=params[:user]
   userid=var[:user_id]
   emailid=var[:email]
   #@users=User.find_by_user_id(userid)
   @users=User.find_by_user_id(vari[:user_id])
   #if 1
	if vari[:email]==@users[:email]
        flash[:notice] = " Welcome #{@user.user_id}!"
	redirect_to movies_path	
   else
	   flash[:notice] = "Wrong Username/Password.Try again. "
	   
   end
 end
def destroy
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	def set_current_user
		@current_user ||= session[:session_token]&& User.find_by_session_token(session[:session_token])
	end
end

app/controllers/movies_controller.rb
# This file is app/controllers/movies_controller.rb
class MoviesController < ApplicationController
before_filter :set_current_user
  def index
    @movies = Movie.all
  end

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # Look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


 def new
  # default: render 'new' template
 end

 def create

   vari=params[:user]
   #var=params[:user]
   userid=vari[:user_id]
   emailid=vari[:email]
   #@users=User.find_by_user_id(userid)
   @user=User.find_by_user_id(vari[:user_id])
    if @user==nil
     flash[:notice] = "Wrong Username/Password.Try again. "
   redirect_to login_path
    
        elsif vari[:email]==nil ||vari[:user_id]==nil
        flash[:notice] = " Enter the complete form details"
	redirect_to login_path	

	elsif vari[:email]==@user[:email]
	session[:session_token] = @user.session_token

        flash[:notice] = " Welcome #{@user.user_id}!"
	redirect_to movies_path	
   else
	   flash[:notice] = "Wrong Username/Password.Try again. "
	   redirect_to login_path
   end
 end
def destroy
session[:session_token]=nil
redirect_to movies_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


 def new
  # default: render 'new' template
 end

 def create

 vari=params[:user]
 #var=params[:user]
 userid=vari[:user_id]
 @user=User.find_by_user_id(userid)
 
if @user==nil
  # @user = User.create!(params[:user])
	user=User.create_user!(vari)
   flash[:notice] = "#{user.user_id} was successfully created."
   
   redirect_to login_path

else

flash[:notice] = "Sorry,this user-id is taken.Try again. "
redirect_to new_user_path
end







 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    -if !@current_user
      = button_to 'Sign up/Login', login_path, method: :get
    -else
      you are logged in as #{@current_user.user_id}
      = button_to 'Logout', logout_path, method: :delete  
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/movies/edit.html.haml
-# in app/views/movies/edit.html.haml
%h1 Edit Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/index.html.haml
-# This file is app/view/movies/index.html.haml
%h1 All Movies

%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
-# in app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path, :method => :post do

  = label :movie, :title, 'Title'
  = text_field :movie, :title

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h1 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit info', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path

app/views/users/new.html.haml
-# in app/views/users/new.html.haml
%h1 Create New Users
= form_tag users_path, :method => :post  do
  = label :user, :user_id, 'User ID'
  = text_field :user, :user_id

  = label :user,:email,'E-Mail'
  = text_field :user, :email

  = submit_tag 'Create my account'